name: Enterprise DevSecOps Pipeline

on:
  push:
    branches: [main]

env:
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/backend:latest

jobs:

# -----------------------------
# Build Frontend
# -----------------------------

  frontend-build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
         cd frontend 
         rm -rf node_modules
         rm -f package-lock.json 
         npm install
      - name: Build React
        run: |
          cd frontend
          npm install
          npm run build

# -----------------------------
# Build Backend
# -----------------------------

  backend-build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Spring Boot
        run: |
          cd backend
          mvn clean package

# -----------------------------
# Docker Build + Scan
# -----------------------------

  docker-build-scan:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: [frontend-build, backend-build]

    steps:

      - uses: actions/checkout@v4

      # Build Images
      - name: Build Frontend Image
        run: docker build -t frontend-image ./frontend

      - name: Build Backend Image
        run: docker build -t backend-image ./backend

      # Install Trivy
      - uses: aquasecurity/setup-trivy@v0.2.0

      # Scan Images
      - name: Scan Frontend Image
        run: |
          trivy image --severity CRITICAL,HIGH,MEDIUM,LOW --exit-code 0 frontend-image

      - name: Scan Backend Image
        run: |
          trivy image --severity CRITICAL,HIGH,MEDIUM,LOW --exit-code 0 backend-image

      # Login DockerHub
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Tag Images
      - name: Tag Images
        run: |
          docker tag frontend-image $FRONTEND_IMAGE
          docker tag backend-image $BACKEND_IMAGE

      # Push Images
      - name: Push Images
        run: |
          docker push $FRONTEND_IMAGE
          docker push $BACKEND_IMAGE

# -----------------------------
# Pull Images and Run Containers
# -----------------------------

  run-container:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: docker-build-scan

    steps:

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Images
        run: |
          docker pull $FRONTEND_IMAGE
          docker pull $BACKEND_IMAGE

      - name: Run Backend
        run: |
          docker run -d -p 8080:8080 $BACKEND_IMAGE
          sleep 20

      - name: Run Frontend
        run: |
          docker run -d -p 3000:80 $FRONTEND_IMAGE

# -----------------------------
# DAST Scan
# -----------------------------

  dast-test:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: run-container

    steps:
    - name: Wait for application
      run: sleep 30

    - name: Create ZAP report folder
      run: mkdir -p zap-report

    - name: Run ZAP Scan
      run: |
        docker run --network host \
          -v $(pwd)/zap-report:/zap/wrk/:rw \
          -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py \
          -t http://localhost:8080 \
          -r report.html
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-report

# -----------------------------
# Image Signing
# -----------------------------

  image-sign:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: dast-test

    steps:

      - uses: sigstore/cosign-installer@v3

      - name: Sign Backend Image
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY $BACKEND_IMAGE
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Sign Frontend Image
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY $FRONTEND_IMAGE
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}